# Generated by Django 4.1.3 on 2022-12-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='template',
        ),
        migrations.AddField(
            model_name='employee',
            name='template',
            field=models.ManyToManyField(blank=True, related_name='checklist_template', to='hr.template'),
        ),
    ]
