# Generated by Django 4.1.3 on 2022-12-14 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_employee_departement_alter_employee_manager_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee',
            new_name='name',
        ),
    ]
