# Generated by Django 4.1.3 on 2022-12-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_employee_departement_alter_employee_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sign_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(default=None),
        ),
    ]
