# Generated by Django 4.1.3 on 2022-12-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_employee_sign_date_alter_employee_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='sign_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
