# Generated by Django 4.1.3 on 2022-12-28 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0004_remove_task_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('company', 'Company'), ('handbook', 'Handbook'), ('contacts', 'Contacts'), ('training', 'Training')], default='training', max_length=50, unique=True)),
                ('content', models.TextField()),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.department')),
            ],
        ),
    ]
