# Generated by Django 4.1.3 on 2022-12-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('training', 'Training'), ('company', 'Company'), ('handbook', 'Handbook'), ('contacts', 'Contacts')], default='training', max_length=50),
        ),
    ]
