# Generated by Django 4.1.3 on 2022-12-29 00:32

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('training', 'Training'), ('company', 'Company'), ('handbook', 'Handbook')], default='training', max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
